apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: booking-service
    version: {{ .Values.version }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: booking-service
      version: {{ .Values.version }}

  template:
    metadata:
      labels:
        app: booking-service
        version: {{ .Values.version }}

    spec:
      containers:
        - name: {{ .Chart.Name }}

          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- if .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          {{- end }}

          {{- if .Values.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: 8080
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          {{- end }}